#!/usr/bin/env bun
// ─── Update disposable email domain list ───
// Fetches from multiple CC0/permissive-licensed sources, merges, dedupes,
// and regenerates src/data/disposable.ts.
//
// Falls back to data/disposable-fallback.txt.gz if all upstream fetches fail.
// Updates the fallback snapshot whenever fresh data is fetched.
//
// Run: bun run update-disposable

import { gunzipSync, gzipSync } from 'node:zlib';
import { readFileSync, writeFileSync } from 'node:fs';

interface Source {
  url: string;
  license: string;
  format: 'lines' | 'json';
}

const SOURCES: Source[] = [
  {
    url: 'https://raw.githubusercontent.com/disposable-email-domains/disposable-email-domains/main/disposable_email_blocklist.conf',
    license: 'CC0',
    format: 'lines',
  },
  {
    url: 'https://raw.githubusercontent.com/7c/fakefilter/main/txt/data.txt',
    license: 'MIT',
    format: 'lines',
  },
  {
    url: 'https://raw.githubusercontent.com/wesbos/burner-email-providers/master/emails.txt',
    license: 'ISC',
    format: 'lines',
  },
  {
    url: 'https://raw.githubusercontent.com/ivolo/disposable-email-domains/master/index.json',
    license: 'MIT',
    format: 'json',
  },
];

const OUTPUT_PATH = 'src/data/disposable.ts';
const FALLBACK_PATH = 'data/disposable-fallback.txt.gz';

function parseLines(text: string): string[] {
  return text
    .split('\n')
    .map(line => line.trim().toLowerCase())
    .filter(line => line && !line.startsWith('#') && !line.startsWith('//'));
}

function isValidDomain(d: string): boolean {
  return /^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$/.test(d);
}

async function fetchSource(source: Source): Promise<string[]> {
  console.log(`  Fetching ${source.url} (${source.license})...`);
  try {
    const response = await fetch(source.url, { signal: AbortSignal.timeout(15_000) });
    if (!response.ok) {
      console.error(`  ⚠ Failed: ${response.status} — skipping`);
      return [];
    }

    const text = await response.text();
    let domains: string[];

    if (source.format === 'json') {
      try {
        const parsed = JSON.parse(text);
        domains = (Array.isArray(parsed) ? parsed : [])
          .map((d: unknown) => String(d).trim().toLowerCase())
          .filter(Boolean);
      } catch {
        console.error(`  ⚠ Bad JSON — skipping`);
        return [];
      }
    } else {
      domains = parseLines(text);
    }

    const valid = domains.filter(isValidDomain);
    console.log(`  → ${valid.length} valid domains`);
    return valid;
  } catch (err) {
    console.error(`  ⚠ Fetch error: ${err} — skipping`);
    return [];
  }
}

function loadFallback(): string[] {
  console.log(`\n⚠ All upstream sources failed. Loading fallback from ${FALLBACK_PATH}...`);
  const compressed = readFileSync(FALLBACK_PATH);
  const text = gunzipSync(compressed).toString('utf-8');
  const domains = parseLines(text).filter(isValidDomain);
  console.log(`  → ${domains.length} domains from fallback`);
  return domains;
}

function updateFallback(domains: string[]): void {
  const text = domains.join('\n') + '\n';
  const compressed = gzipSync(Buffer.from(text), { level: 9 });
  writeFileSync(FALLBACK_PATH, compressed);
  console.log(`Updated fallback: ${FALLBACK_PATH} (${(compressed.length / 1024).toFixed(0)}K)`);
}

function generateSource(unique: string[], fromFallback: boolean): string {
  const sourceList = SOURCES
    .map(s => `//   - ${s.url}\n//     License: ${s.license}`)
    .join('\n');

  const fallbackNote = fromFallback
    ? '\n// ⚠ Generated from local fallback (upstream sources unavailable)'
    : '';

  return `// ─── Disposable email domain detection ───
// Auto-generated by scripts/update-disposable-list.ts — do not edit manually.
//
// Sources:
${sourceList}
//${fallbackNote}
// Generated: ${new Date().toISOString()}
// Domains: ${unique.length}

const DISPOSABLE_DOMAINS_LIST: string[] = ${JSON.stringify(unique, null, 2)};

const DISPOSABLE_SET = new Set(DISPOSABLE_DOMAINS_LIST);

/**
 * Check if a domain is a known disposable email service.
 * Also checks parent domains for wildcard subdomain matching
 * (e.g., anything.guerrillamail.com).
 */
export function isDisposableDomain(domain: string): boolean {
  const lower = domain.toLowerCase();

  // Exact match
  if (DISPOSABLE_SET.has(lower)) return true;

  // Check parent domains (wildcard subdomain matching)
  const parts = lower.split('.');
  for (let i = 1; i < parts.length - 1; i++) {
    const parent = parts.slice(i).join('.');
    if (DISPOSABLE_SET.has(parent)) return true;
  }

  return false;
}

/**
 * Get the size of the bundled disposable domain list.
 */
export function getDisposableListSize(): number {
  return DISPOSABLE_SET.size;
}
`;
}

async function main() {
  console.log('Updating disposable domain list...\n');

  const results = await Promise.all(SOURCES.map(fetchSource));
  const merged = results.flat();
  let unique: string[];
  let fromFallback = false;

  if (merged.length === 0) {
    unique = loadFallback();
    fromFallback = true;
  } else {
    unique = [...new Set(merged)].sort();
    console.log(`\nMerged: ${merged.length} total → ${unique.length} unique domains`);
    updateFallback(unique);
  }

  const source = generateSource(unique, fromFallback);
  await Bun.write(OUTPUT_PATH, source);
  console.log(`\n✓ Written to ${OUTPUT_PATH} (${unique.length} domains)`);
}

main().catch(err => {
  console.error('Error:', err);
  process.exit(1);
});
