#!/usr/bin/env bun
// ─── Update disposable email domain list ───
// Fetches the CC0 disposable-email-domains list and updates src/data/disposable.ts.
// Run: bun run update-disposable

const LIST_URL = 'https://raw.githubusercontent.com/disposable-email-domains/disposable-email-domains/main/disposable_email_blocklist.conf';
const OUTPUT_PATH = 'src/data/disposable.ts';

async function main() {
  console.log('Fetching disposable domain list...');

  const response = await fetch(LIST_URL);
  if (!response.ok) {
    throw new Error(`Failed to fetch list: ${response.status} ${response.statusText}`);
  }

  const text = await response.text();
  const domains = text
    .split('\n')
    .map(line => line.trim().toLowerCase())
    .filter(line => line && !line.startsWith('#') && !line.startsWith('//'))
    .sort();

  const unique = [...new Set(domains)];
  console.log(`Fetched ${unique.length} unique domains`);

  // Generate TypeScript source
  const source = `// ─── Disposable email domain detection ───
// Auto-generated by scripts/update-disposable-list.ts
// Source: ${LIST_URL}
// License: CC0
// Generated: ${new Date().toISOString()}
// Domains: ${unique.length}

const DISPOSABLE_DOMAINS_LIST: string[] = ${JSON.stringify(unique, null, 2)};

const DISPOSABLE_SET = new Set(DISPOSABLE_DOMAINS_LIST);

/**
 * Check if a domain is a known disposable email service.
 * Also checks parent domains for wildcard subdomain matching
 * (e.g., anything.guerrillamail.com).
 */
export function isDisposableDomain(domain: string): boolean {
  const lower = domain.toLowerCase();

  // Exact match
  if (DISPOSABLE_SET.has(lower)) return true;

  // Check parent domains (wildcard subdomain matching)
  const parts = lower.split('.');
  for (let i = 1; i < parts.length - 1; i++) {
    const parent = parts.slice(i).join('.');
    if (DISPOSABLE_SET.has(parent)) return true;
  }

  return false;
}

/**
 * Get the size of the bundled disposable domain list.
 */
export function getDisposableListSize(): number {
  return DISPOSABLE_SET.size;
}
`;

  await Bun.write(OUTPUT_PATH, source);
  console.log(`Written to ${OUTPUT_PATH} (${unique.length} domains)`);
}

main().catch(err => {
  console.error('Error:', err);
  process.exit(1);
});
