#!/usr/bin/env bun
// ─── Update disposable email domain list ───
// Fetches from multiple CC0/permissive-licensed sources, merges, dedupes,
// and regenerates src/data/disposable.ts.
// Run: bun run update-disposable

interface Source {
  url: string;
  license: string;
  format: 'lines' | 'json';
}

const SOURCES: Source[] = [
  {
    url: 'https://raw.githubusercontent.com/disposable-email-domains/disposable-email-domains/main/disposable_email_blocklist.conf',
    license: 'CC0',
    format: 'lines',
  },
  {
    url: 'https://raw.githubusercontent.com/7c/fakefilter/main/txt/data.txt',
    license: 'MIT',
    format: 'lines',
  },
  {
    url: 'https://raw.githubusercontent.com/wesbos/burner-email-providers/master/emails.txt',
    license: 'ISC',
    format: 'lines',
  },
  {
    url: 'https://raw.githubusercontent.com/ivolo/disposable-email-domains/master/index.json',
    license: 'MIT',
    format: 'json',
  },
];

const OUTPUT_PATH = 'src/data/disposable.ts';

function parseLines(text: string): string[] {
  return text
    .split('\n')
    .map(line => line.trim().toLowerCase())
    .filter(line => line && !line.startsWith('#') && !line.startsWith('//'));
}

function isValidDomain(d: string): boolean {
  return /^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$/.test(d);
}

async function fetchSource(source: Source): Promise<string[]> {
  console.log(`  Fetching ${source.url} (${source.license})...`);
  const response = await fetch(source.url);
  if (!response.ok) {
    console.error(`  ⚠ Failed to fetch ${source.url}: ${response.status} — skipping`);
    return [];
  }

  const text = await response.text();
  let domains: string[];

  if (source.format === 'json') {
    try {
      const parsed = JSON.parse(text);
      domains = (Array.isArray(parsed) ? parsed : [])
        .map((d: unknown) => String(d).trim().toLowerCase())
        .filter(Boolean);
    } catch {
      console.error(`  ⚠ Failed to parse JSON from ${source.url} — skipping`);
      return [];
    }
  } else {
    domains = parseLines(text);
  }

  const valid = domains.filter(isValidDomain);
  console.log(`  → ${valid.length} valid domains`);
  return valid;
}

async function main() {
  console.log('Fetching disposable domain lists from multiple sources...\n');

  const results = await Promise.all(SOURCES.map(fetchSource));
  const merged = results.flat();
  const unique = [...new Set(merged)].sort();

  console.log(`\nMerged: ${merged.length} total → ${unique.length} unique domains`);

  // Build source attribution header
  const sourceList = SOURCES
    .map(s => `//   - ${s.url}\n//     License: ${s.license}`)
    .join('\n');

  const source = `// ─── Disposable email domain detection ───
// Auto-generated by scripts/update-disposable-list.ts — do not edit manually.
//
// Sources:
${sourceList}
//
// Generated: ${new Date().toISOString()}
// Domains: ${unique.length}

const DISPOSABLE_DOMAINS_LIST: string[] = ${JSON.stringify(unique, null, 2)};

const DISPOSABLE_SET = new Set(DISPOSABLE_DOMAINS_LIST);

/**
 * Check if a domain is a known disposable email service.
 * Also checks parent domains for wildcard subdomain matching
 * (e.g., anything.guerrillamail.com).
 */
export function isDisposableDomain(domain: string): boolean {
  const lower = domain.toLowerCase();

  // Exact match
  if (DISPOSABLE_SET.has(lower)) return true;

  // Check parent domains (wildcard subdomain matching)
  const parts = lower.split('.');
  for (let i = 1; i < parts.length - 1; i++) {
    const parent = parts.slice(i).join('.');
    if (DISPOSABLE_SET.has(parent)) return true;
  }

  return false;
}

/**
 * Get the size of the bundled disposable domain list.
 */
export function getDisposableListSize(): number {
  return DISPOSABLE_SET.size;
}
`;

  await Bun.write(OUTPUT_PATH, source);
  console.log(`Written to ${OUTPUT_PATH} (${unique.length} domains)`);
}

main().catch(err => {
  console.error('Error:', err);
  process.exit(1);
});
